src/album/album.service.spec.ts
src/album/album.service.ts
src/album/models/album.query-parameters.ts
src/artist/artist.service.spec.ts
src/file/file.exceptions.ts
src/file/file.service.spec.ts
src/file/file.service.ts
src/release/models/release.query-parameters.ts
src/release/release.service.spec.ts
src/release/release.service.ts
src/song/song.service.spec.ts
src/song/song.service.ts
src/track/models/track.query-parameters.ts
src/track/track.service.spec.ts
src/track/track.service.ts

Deletion methods used to take the same input as 'getOne' and 'getMany' methods.
However, Prisma and their 'uniqueWhereInput's are not compatible with these methods, which would cause runtime errors
Therefore, incompatible methods now take a dedicated input, derived from the related 'WhereInput'

Services: Fix some Deletion methods

---

front/src/api.ts
front/src/query.ts

'prepareMeeloQuery' would return a ReactQuery's Query as disabled when one of the query's parameters is undefined.
Now, it will also disable a query if a parameter is null. This happens on a compilation release's page, where the artist's id is null

Front: Fix 'prepareMeeloQuery'

---

front/src/components/player/player.tsx
front/src/pages/albums/index.tsx
front/src/pages/artists/index.tsx
front/src/pages/songs/index.tsx

Faulty selection was caused by using a parameter from SSR when the page was not hydrated. Therefore, it would always select the 'global' library.
When SSR Props return a null library slug, reparse the url to get it.
Closes #225

Front: Fix Library Selection

---

dev/Dockerfile
front/src/api/api.ts
front/src/components/authentication/authentication-form.tsx
front/src/components/list-item/item.tsx
front/src/components/loading/loading.tsx
front/src/components/settings/libraries-settings.tsx
front/src/components/settings/users-settings.tsx
front/src/components/track-file-info.tsx
front/src/pages/_app.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/settings/[[...panel]].tsx
front/src/theme.ts
src/album/album.controller.ts
src/exceptions/not-found.exception.ts
src/file/file.service.ts
src/user/models/create-user.dto.ts
src/user/models/user.query-params.ts

Multiple Quick fixes and improvements:
- Closes #338
- Release Page: Artist Title is a link
- Fix Theme to avoid having to set text color for transparent buttons
- Release Page: Avoid layout shift on artist load
- Rework of the /albums/:id/videos route to have a better / smarter selection
- Release Page: Use rework of /albums/:id/video instead of multiple queries
- Update 404 error response to match the other exceptions/error messages
- Library Settings Page: Fix icon alignment on narrow view ports
- User Creation Route: Remove 'admin' field from DTO

Better album videos select

---

front/src/pages/releases/[slugOrId].tsx
server/src/metadata/metadata.service.ts

On file parsing, if the release was more recent that the album, a wrong condition would always set the album's date as the release's date

Metadata Parsing: Fix Album Date update condition

---

Dockerfile
server/package.json
server/src/settings/models/settings.ts
server/src/settings/settings.exception.ts
server/src/settings/settings.service.spec.ts
server/src/settings/settings.service.ts

Using class validator instead of parsing/validating 'by hand'.
This will be useful for future settings fields (eg, see #413)

Settings validation: Use 'class-validator'

---

front/src/api/api.ts
front/src/components/infinite/infinite-resource-view/infinite-song-view.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/pages/artists/[slugOrId]/index.tsx
server/src/scanner/parser.service.spec.ts
server/src/scanner/parser.service.ts
server/src/song/song.controller.ts
server/src/song/song.service.ts

Get Rare Songs

---

server/src/illustration/illustration.service.spec.ts
server/src/illustration/illustration.service.ts

Closes #667 
I though it would look somewhat better, but it does not change anything really

Server: Compute Illustration Blurhash using aspect ratio

---

front/src/contexts/keybindings.tsx

The `/` and `s` bindings did not check whether we focused an `input`.
We overload `useKey` to do this check for every binding

Front: Fix Keybinding Trigger when focus on input

---

front/src/api/api.ts
front/src/components/infinite/infinite-resource-view/infinite-video-view.tsx
front/src/pages/artists/[slugOrId]/videos.tsx
front/src/pages/videos/index.tsx
server/src/video/video.controller.ts
server/src/video/video.service.spec.ts
server/src/video/video.service.ts

Allow Shuffling Videos

---

.github/actions/cache-matcher/action.yml
.github/workflows/matcher.yml
matcher/matcher/bootstrap.py
matcher/matcher/context.py
matcher/matcher/matcher/album.py
matcher/matcher/matcher/artist.py
matcher/matcher/matcher/common.py
matcher/matcher/providers/allmusic.py
matcher/matcher/providers/base.py
matcher/matcher/providers/boilerplate.py
matcher/matcher/providers/discogs.py
matcher/matcher/providers/domain.py
matcher/matcher/providers/factory.py
matcher/matcher/providers/features.py
matcher/matcher/providers/genius.py
matcher/matcher/providers/metacritic.py
matcher/matcher/providers/musicbrainz.py
matcher/matcher/providers/wikipedia.py
matcher/tests/providers/allmusic.py
matcher/tests/providers/discogs.py
matcher/tests/providers/genius.py
matcher/tests/providers/metacritic.py
matcher/tests/providers/musicbrainz.py
matcher/tests/providers/wikipedia.py

To avoid calling a provider that cannot provide info we need, we define a list of feature each provider has.
This changes the internal structure of providers, but it helps us keep provider classes simple, with only the features we need, and not obligatory 'empty' functions required by inheritance
--
This speeds up the matching test by 20/30%

Matcher: Provider 'features'

---

front/src/models/song.ts
front/src/pages/releases/[slugOrId].tsx

Previously, server-side, we ordered videos in the order of an album (this was a dirty hack though).
The way prisma queries work do not allow us to sort videos using a specific release.
As a workaround, we sort video on client-side. The ordering is optimized so that we go through the tracklist only as many times as there are videos to sort. We use the song group to order them.
The result is: videos are sorted in the order of the tracklist.

Front: Order Videos using Tracklist

---

front/src/pages/search/[[...query]].tsx

We prevent browser to suggest and correct user input in search bar. When this happens, it can replace text, save, trigger a fetch and change the search results before user can do anything

Front: Disable Spellcheck in Search Field

---

server/package.json

Remove dependency of top-level `.env` file to setup tests.

Server: Simplify env setup for tests

---

front/src/models/illustration.ts

Fix illustration colours not being 6-chars long, leading to transparent surfaces

Front: Normalize color for CSS

---

scanner/internal/config/user_settings.go
scanner/internal/parser/embedded.go
scanner/internal/tasks/illustration.go
settings.json

When generating a thumbnail for a video, we now first check if it contains an embedded illustration. If it does, we use that as the thumbnail.
In case it doesn't, we fall back to the existing implementation of using a frame from the video.

Use the embeded video illustration as thumbnail if one exists

---

scanner/internal/parser/embedded.go

If `useEmbeddedThumbnails` is set to true, we don't extract the embedded illustration for use as album cover, so we can instead use it as thumbnail.  
However, this currently also skips using the embedded illustration for non-video songs, despite the embedded illustration not being used as a thumbnail (as far as i know). This results in music albums without a cover.jpg being cover-less without real purpose.
As a side-note, i wonder if the check could be removed entirely, to me it seems better to have a thumbnail as album cover rather than no album cover at all (especially since setting `useEmbeddedThumbnails` to false will result in the would-be thumbnails being used as album covers instead)
And i apologize for not catching during the original PR, i misunderstood what this chunk of code …

Only skip using the embedded thumbnail as illustrations for videos

---

front/src/contexts/keybindings.tsx

On Firefox, pressing the `/` key opens a bar at the bottom of the screen for the "quick find" feature.
This PR prevents that behavior, so users trying to go to the search page with the shortcut don't end up opening quick find.

Prevent default on "/" keypress event to prevent quick find from opening

---

docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml

This should close #969 cause as explained the profiles definitions do not make any sense in this context as the compose is created to only support the cpu/default option which is good enough for music and the occasionally odd video.

Docker: remove unused profile definitions

---

front/apps/web/src/components/player/controls/minimized.tsx
front/apps/web/src/components/player/controls/slider.tsx
front/apps/web/src/components/player/index.tsx

Front: Add progress + rewind button on minimised player
