Arthi-chaud/Meelo

src/album/album.controller.spec.ts
src/album/album.controller.ts
src/artist/artist.controller.ts
src/id/id.exception.ts
src/id/id.pipe.ts
src/library/library.controller.ts
src/release/release.controller.ts
src/song/song.controller.ts
src/track/track.controller.ts

Controller: Parse Id: Create custom Pipe

---

src/metadata/metadata.service.ts

Metadata Service: Fix File Type identification for videos

---

src/album/album.controller.spec.ts
src/album/album.controller.ts
src/artist/artist.controller.spec.ts
src/artist/artist.controller.ts
src/library/library.controller.spec.ts
src/library/library.controller.ts
src/pagination/models/paginated-response.spec.ts
src/pagination/models/paginated-response.ts
src/pagination/models/pagination-parameters.ts
src/release/release.controller.spec.ts
src/release/release.controller.ts
src/song/song.controller.spec.ts
src/song/song.controller.ts
src/track/track.controller.spec.ts
src/track/track.controller.ts

On routes with list response, add pagination links,
closes #52

Controller: Paginated response

---

src/album/album.controller.spec.ts
src/album/album.controller.ts
src/album/album.module.ts
src/release/release.controller.spec.ts
src/release/release.controller.ts
src/track/models/tracklist.model.ts
src/track/track.service.ts

Tracklisting

---

src/exceptions/meelo-exception.ts
src/file/file.controller.spec.ts
src/file/file.controller.ts
src/file/file.exceptions.ts
src/file/file.module.ts
src/file/file.service.spec.ts
src/file/file.service.ts
src/file/models/file.query-parameters.ts
src/library/library.controller.spec.ts
src/release/release.controller.spec.ts
src/song/song.controller.spec.ts
src/track/track.controller.spec.ts
src/track/track.service.ts

Stream source files

---

.vscode/settings.json
src/metadata/metadata.service.spec.ts
src/metadata/metadata.service.ts

Track: Remove Track's Video Prefix on metadata parsing

---

src/library/library.controller.ts
src/library/library.service.ts

Library: On deletion, delete related tracks & files + controller deletion route

---

src/artist/artist.controller.ts

Artist Controller: Check artist exists on song fetch

---

src/album/album.controller.ts
src/artist/artist.controller.ts
src/artist/artist.module.ts
src/artist/artist.service.spec.ts
src/pagination/models/paginated-response.spec.ts
src/pagination/models/paginated-response.ts
src/song/song.controller.spec.ts
src/song/song.controller.ts
src/track/models/track.query-parameters.ts
src/track/track.controller.spec.ts
src/track/track.controller.ts
src/track/track.service.spec.ts

Get Videos by song, album & artist

---

.github/workflows/unit-tests.yml
src/artist/artist.controller.ts
src/artist/artist.service.spec.ts
src/artist/artist.service.ts
src/library/library.controller.spec.ts
src/library/library.controller.ts
src/song/song.service.spec.ts
yarn.lock

Get only Album Artists

---

nest-cli.json
src/app.module.ts
src/artist/artist.service.ts
src/release/models/release.query-parameters.ts
src/release/release.service.ts
src/search/search.controller.spec.ts
src/search/search.controller.ts
src/search/search.module.ts
src/search/search.service.spec.ts
src/search/search.service.ts

Search Module

---

src/album/album.exceptions.ts
src/illustration/illustration.service.ts
src/release/models/reassign-release.dto.ts
src/release/release.controller.spec.ts
src/release/release.controller.ts
src/release/release.service.spec.ts
src/release/release.service.ts

Release: Reassign to album

---

src/lyrics/lyrics.service.ts
src/lyrics/models/update-lyrics.dto.ts
src/repository/repository.service.ts
src/search/search.controller.ts
src/song/song.controller.spec.ts
src/song/song.controller.ts

Lyrics CRUD Routes

---

src/album/album.controller.ts
src/album/album.service.spec.ts
src/album/album.service.ts
src/artist/artist.controller.spec.ts
src/artist/artist.controller.ts
src/artist/artist.service.spec.ts
src/artist/artist.service.ts
src/file-manager/file-manager.service.ts
src/file/file.service.ts
src/genre/genre.controller.spec.ts
src/genre/genre.controller.ts
src/genre/genre.service.spec.ts
src/genre/genre.service.ts
src/library/library.controller.ts
src/library/library.service.ts
src/lyrics/lyrics.service.spec.ts
src/lyrics/lyrics.service.ts
src/release/release.controller.ts
src/release/release.service.spec.ts
src/release/release.service.ts
src/repository/repository.service.ts
src/song/song.controller.ts
src/song/song.service.spec.ts
src/song/song.service.ts
src/track/track.service.spec.ts
src/track/track.service.ts

Add a 'exists' and 'throwIfNotExist' method in repository services

---

README.md

Readme:  Introduction + features

---

src/metadata/metadata.service.spec.ts
src/metadata/metadata.service.ts

Add « Remaster » as title extension

---

front/src/components/appbar/appbar.tsx
front/src/components/infinite/infinite-grid.tsx
front/src/components/infinite/infinite-list.tsx
front/src/components/infinite/infinite-view.tsx
front/src/pages/albums/index.tsx
front/src/pages/artists/index.tsx
front/src/query.ts

Front: Add toggle in infinite view

---

front/package.json
front/src/api.ts
front/src/components/infinite/infinite-view.tsx
front/src/components/list-item/album-item.tsx
front/src/components/list-item/song-item.tsx
front/src/pages/albums/index.tsx
front/src/pages/artists/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/songs/index.tsx
front/src/query.ts
front/src/utils/sorting.ts
front/yarn.lock

Front: Items List: Sorting

---

front/next.config.js
front/src/api.ts
front/src/components/illustration.tsx
front/src/pages/_app.tsx

- On SSR set a hostname in the nextjs config file to nestjs.
- Remove hardcoded 'localhost' in code
- Fix illustration loading

Front: Make Production Ready

---

front/src/components/illustration.tsx
front/src/components/list-item/album-item.tsx
front/src/components/list-item/artist-item.tsx
front/src/components/list-item/song-item.tsx
front/src/components/tile/album-tile.tsx
front/src/components/tile/artist-tile.tsx
front/src/components/tile/tile.tsx
front/src/pages/releases/[slugOrId].tsx

The Illustration component manages the error fallback itself, by using an icon to render on error

Front: Illustration fallback

---

front/src/components/list-item/album-item.tsx
front/src/components/list-item/artist-item.tsx
front/src/components/list-item/item-button.tsx
front/src/components/list-item/item.tsx
front/src/components/list-item/song-item.tsx
front/src/components/tile/artist-tile.tsx
front/src/pages/releases/[slugOrId].tsx

Fixes here and there of text alignment and justification.
Also little rework of the release page design to make it more responsive

Front: Consistent text alignment

---

front/package.json
front/src/api.ts
front/src/components/appbar/appbar.tsx
front/src/components/list-item/song-item.tsx
front/src/components/player/controls.tsx
front/src/components/player/player.tsx
front/src/models/track.ts
front/src/pages/_app.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/state/playerSlice.ts
front/src/state/store.ts
front/src/utils/formatDuration.ts
front/yarn.lock

Front: Basic Player

---

src/album/album.controller.spec.ts
src/album/album.controller.ts
src/album/album.service.ts
src/artist/artist.controller.spec.ts
src/artist/artist.controller.ts
src/artist/artist.service.ts
src/file/file.service.ts
src/genre/genre.controller.spec.ts
src/genre/genre.controller.ts
src/genre/genre.service.ts
src/illustration/illustration.service.spec.ts
src/illustration/illustration.service.ts
src/library/library.controller.spec.ts
src/library/library.controller.ts
src/library/library.service.ts
src/lyrics/lyrics.service.ts
src/release/release.controller.spec.ts
src/release/release.controller.ts
src/release/release.service.ts
src/repository/repository.service.ts
src/search/search.controller.spec.ts
src/search/search.controller.ts
src/song/song.controller.spec.ts
src/song/song.controller.ts
src/song/song.module.ts
src/song/song.service.ts
src/track/track.controller.spec.ts
src/track/track.controller.ts
src/track/track.service.ts

In response, provide a link to a resource's illustration only if it exists.
Also, will provide a direct link to the resource. For example: a song's illustration link will be the same as its master track's
Close #187

Illustration link optimization

---

front/src/components/appbar/appbar.tsx
front/src/components/infinite/infinite-grid.tsx
front/src/components/infinite/infinite-view.tsx
front/src/components/list-item/album-item.tsx
front/src/components/list-item/item.tsx
front/src/components/player/controls.tsx
front/src/components/player/player.tsx
front/src/pages/_app.tsx
front/src/pages/artists/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/utils/formatDuration.ts

Front: Refactor Player UI

---

src/identifier/id.pipe.ts

ParseId Pipe: Use Regex to check if input is strictly a number

---

src/album/album.controller.spec.ts
src/album/album.controller.ts
src/main.ts

+ Set API Url for Swagger
Closes #216

Remove API Route duplicates

---

front/src/components/appbar/appbar.tsx

Front: Appbar icon is a link to root

---

src/song/song.controller.spec.ts
src/song/song.controller.ts
src/song/song.service.spec.ts
src/song/song.service.ts

Find the versions of a song

---

front/src/api.ts
front/src/components/appbar/appbar.tsx
front/src/components/appbar/drawer.tsx
front/src/components/infinite/infinite-view.tsx
front/src/pages/search/index.tsx

Front: Search page

---

src/library/library.controller.ts
src/library/library.service.ts

Library: Refresh a file metadata when md5checksum changed

---

front/src/api.ts
front/src/components/player/player.tsx
front/src/theme.ts
src/file/file.service.ts
src/main.ts

- Fix MIME type in HTTP Response
- Add Metadata to navigator
- Fix glitchy player layout in front

Front: audio player enhancement

---

src/file/file.service.ts

File Service: Stream: Attachment name is a slug

---

front/src/api.ts
front/src/components/infinite/infinite-grid.tsx
front/src/components/player/player.tsx
front/src/components/tile/tile.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/theme.ts

Closes #234 
Closes #238 
Closes #231
Closes #229

Front: Various layout fixes and error handling

---

front/src/api.ts
front/src/components/appbar/drawer.tsx
front/src/components/player/controls.tsx
front/src/models/library-task-response.ts
front/src/pages/search/index.tsx
front/src/utils/sorting.ts
package.json
src/file-manager/file-manager.service.ts
src/file/file.service.ts
src/library/library.controller.ts
src/library/library.service.ts
src/library/models/library-task.response.ts
yarn.lock

- Optimize file metadata refresh
- Front: functional 'Refresh Library' button
- Player: ellipsis on long titles
Closes #245 
Closes #173

Layout and file management optimization

---

front/next.config.js
front/package.json
front/src/components/illustration.tsx
front/yarn.lock
nest-cli.json
src/illustration/illustration.controller.ts
src/illustration/illustration.service.ts
src/illustration/models/illustration-dimensions.dto.ts
src/main.ts
src/settings/models/settings.ts

Illustration controller allows image resizing and compression
Closes #250
Closes #179

Illustration resize

---

front/src/api.ts
src/app.module.ts
src/file/file.controller.spec.ts
src/library/library.controller.spec.ts
src/library/library.controller.ts
src/library/library.module.ts
src/library/library.service.spec.ts
src/library/library.service.ts
src/song/song.service.ts
src/tasks/models/task.response.ts
src/tasks/tasks.controller.ts
src/tasks/tasks.module.ts
src/tasks/tasks.service.ts

Create a new Task Module which manages registration/clean/refresh tasks.

Task module

---

front/src/api.ts
front/src/components/infinite/infinite-album-view.tsx
front/src/components/infinite/infinite-artist-view.tsx
front/src/components/infinite/infinite-song-view.tsx
front/src/components/infinite/infinite-view.tsx
front/src/components/list-item/artist-item.tsx
front/src/components/modal-page.tsx
front/src/models/album.ts
front/src/models/artist.ts
front/src/models/release.ts
front/src/models/song.ts
front/src/models/track.ts
front/src/pages/albums/index.tsx
front/src/pages/artists/[slugOrId].tsx
front/src/pages/artists/[slugOrId]/albums.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/artists/[slugOrId]/songs.tsx
front/src/pages/artists/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/search/index.tsx
front/src/pages/songs/index.tsx
front/src/utils/sorting.ts
package.json
src/app.module.ts
src/search/search.controller.ts
src/search/search.service.ts
src/tasks/tasks.controller.ts
yarn.lock

Front: artist page

---

front/src/api.ts
front/src/components/illustration.tsx
front/src/components/list-item/artist-item.tsx
front/src/components/player/controls/text.tsx
front/src/components/tile/artist-tile.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/releases/[slugOrId].tsx
package.json
src/file/file.service.ts
src/main.ts
src/metadata/metadata.service.ts
yarn.lock

Various fixes

---

front/src/components/contextual-menu/release-track-contextual-menu.tsx
front/src/components/contextual-menu/song-contextual-menu.tsx
front/src/components/contextual-menu/track-contextual-menu.tsx
front/src/components/list-item/item.tsx
front/src/components/list-item/release-item.tsx
front/src/components/list-item/track-item.tsx
front/src/components/player/player.tsx
front/src/components/relation-page-header/artist-relation-page-header.tsx
front/src/components/relation-page-header/relation-page-header.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/releases/[slugOrId].tsx
src/file/file.service.ts

Front: Fix Layout issues with ListItems + Fix audio stream on Safari

---

front/src/api.ts
front/src/components/infinite/infinite-album-view.tsx
front/src/components/infinite/infinite-artist-view.tsx
front/src/components/infinite/infinite-release-view.tsx
front/src/components/infinite/infinite-song-view.tsx
front/src/components/infinite/infinite-sortable-view.tsx
front/src/components/infinite/infinite-track-view.tsx
front/src/components/infinite/infinite-view-option.tsx
front/src/components/infinite/infinite-view.tsx
front/src/models/album.ts
front/src/pages/albums/index.tsx
front/src/pages/artists/[slugOrId]/albums.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/search/index.tsx
src/album/album.service.ts

Refactorization of 'InfiniteView' to have a customizable button group, and using it to add a button to choose album type on album list view
Closes #207

Front: album type filtering

---

front/src/components/contextual-menu/album-contextual-menu.tsx
front/src/components/contextual-menu/artist-contextual-menu.tsx
front/src/components/contextual-menu/release-contextual-menu.tsx
front/src/components/contextual-menu/release-track-contextual-menu.tsx
front/src/components/contextual-menu/song-contextual-menu.tsx
front/src/utils/copy-link.ts
src/album/album.service.spec.ts
src/album/album.service.ts
src/song/song.service.ts

Better album type recognition

---

front/src/models/album.ts
prisma/migrations/20221026083004_new_album_types/migration.sql
prisma/schema.prisma
src/album/album.service.spec.ts
src/album/album.service.ts
src/metadata/metadata.service.ts

Extended album types

---

front/src/components/action.ts
front/src/components/appbar/actions.ts
front/src/components/appbar/appbar.tsx
front/src/components/appbar/drawer.tsx
front/src/components/contextual-menu/contextual-menu-item.tsx

Implement dry, generic system to have same actions in both appbar and drawers.
Closes #291

Appbar actions

---

front/src/api.ts
front/src/components/infinite/selectable-infinite-view.tsx
front/src/components/list-item/item.tsx
front/src/components/player/controls.tsx
front/src/models/genre.ts
front/src/pages/404.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/genres/[slugOrId].tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/search/index.tsx

Front: Genre page

---

front/__tests__/state/playerSlice.ts
front/__tests__/state/userSlice.ts
front/package.json
front/src/components/player/player.tsx
front/src/pages/_app.tsx

Front: Player notification

---

src/slug/slug.spec.ts
src/slug/slug.ts

Slugs: Handle Hyphen-like characters

---

front/package.json
front/src/api/api.ts
front/src/components/appbar/appbar.tsx
front/src/components/appbar/drawer.tsx
front/src/components/controls/controls.tsx
front/src/components/illustration.tsx
front/src/components/infinite/infinite-grid.tsx
front/src/components/infinite/infinite-list.tsx
front/src/components/infinite/infinite-view.tsx
front/src/components/infinite/selectable-infinite-view.tsx
front/src/components/loading/loading-item.tsx
front/src/components/loading/loading-page.tsx
front/src/components/loading/loading.tsx
front/src/components/player/controls.tsx
front/src/components/relation-page-header/relation-page-header.tsx
front/src/components/release-tracklist.tsx
front/src/components/settings/libraries-settings.tsx
front/src/components/settings/users-settings.tsx
front/src/pages/_app.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/genres/[slugOrId].tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/songs/[slugOrId]/lyrics.tsx
front/src/theme.ts
front/yarn.lock

Rework on the loading component and fade in on loaded

Front: Loading transitions

---

front/src/components/player/controls.tsx

Reverts Arthi-chaud/Meelo#365, as it made things worse for small view using safari

Revert "Front: Expanded Player: Fix layout fix on safari when dimensions change"

---

server/nest-cli.json
server/package.json
server/public/banner.png
server/public/favicon.ico
server/sonar-project.properties
server/src/app.module.ts
server/src/exceptions/all-exceptions.filter.ts
server/src/public/banner.png
server/src/public/favicon.ico
server/src/public/swagger/script.js
server/src/public/swagger/styles.css
server/src/song/song.controller.spec.ts
server/src/song/song.controller.ts
server/src/swagger/bootstrap.ts

Swagger: Custom css

---

front/src/components/tile-row.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/theme.ts

New component which renders tiles in a scrollable row. Used for:
- Music Videos in release page
- Related releases in release Page
- Albums in artist page

Front: Tile Scrollable Row

---

server/src/metadata/metadata.service.ts
server/src/tasks/tasks.service.ts

Metadata Service: Fix Merge of Genre's Metadata from tags and path

---

server/src/file-manager/file-manager.service.ts
server/src/tasks/tasks.service.ts

Resync Metadata Task: Optimization

---

front/src/components/list-item/item.tsx
front/src/pages/releases/[slugOrId].tsx

Rewrite of the custom 'ListItem' component, using MUI's

Front: 'List Item' component rewrite

---

server/.eslintrc.json
server/src/album/album.service.ts
server/src/app.module.ts
server/src/artist/artist.service.ts
server/src/exceptions/all-exceptions.filter.ts
server/src/genre/genre.service.ts
server/src/illustration/illustration.service.ts
server/src/library/library.service.ts
server/src/logger/logger.module.ts
server/src/logger/logger.ts
server/src/lyrics/lyrics.service.ts
server/src/main.ts
server/src/metadata/metadata.service.ts
server/src/prisma/prisma.service.ts
server/src/release/release.service.ts
server/src/song/song.service.ts
server/src/tasks/tasks.controller.ts
server/src/tasks/tasks.service.ts
server/src/track/track.service.ts

Custom Logger

---

server/src/file-manager/file-manager.service.ts
server/src/library/library.controller.ts
server/src/metadata/metadata.exceptions.ts
server/src/tasks/tasks.module.ts
server/src/tasks/tasks.service.ts

Rewrite of the Candidate Files fetching

---

server/src/track/track.service.spec.ts
server/src/track/track.service.ts

Track Service: Get Master Track: Avoid video when possible

---

front/src/components/player/controls.tsx
front/src/components/release-tracklist.tsx
front/src/components/tile/tile.tsx
front/src/components/track-file-info.tsx
front/src/pages/releases/[slugOrId].tsx

- Fix album artist's name alignment
- Change colors of index and duration labels
- Remove radius on track button's end

Front release page layout improvement

---

front/src/styles.css

Reverts Arthi-chaud/Meelo#406, breaks appbar with expanded player

Revert "Front: Avoid Scroll-gutter to shift content position"

---

server/src/illustration/illustration.service.ts
server/src/library/library.controller.ts
server/src/tasks/tasks.service.ts

File Registration: Avoid Scanning Cover Files

---

front/next.config.js
front/src/api/api.ts
front/src/components/appbar/item-types.tsx
front/src/components/infinite/infinite-resource-view/infinite-video-view.tsx
front/src/components/player/controls.tsx
front/src/components/tile/video-tile.tsx
front/src/models/song.ts
front/src/pages/releases/[slugOrId].tsx
front/src/pages/videos/index.tsx
server/src/library/library.controller.spec.ts
server/src/library/library.controller.ts
server/src/pagination/paginated-response.decorator.ts
server/src/song/models/song-with-video.response.ts
server/src/song/song.controller.spec.ts
server/src/song/song.controller.ts
server/src/song/song.module.ts
server/src/song/song.service.spec.ts
server/src/song/song.service.ts

Videos section

---

front/src/api/api.ts
front/src/components/external-id-badge.tsx
front/src/components/relation-page-header/artist-relation-page-header.tsx
front/src/models/album.ts
front/src/models/artist.ts
front/src/models/external-id.ts
front/src/models/song.ts
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/songs/[slugOrId]/[...tab].tsx

Front: Add external ids

---

server/src/metadata/metadata.exceptions.ts
server/src/metadata/metadata.service.spec.ts
server/src/metadata/metadata.service.ts
server/src/metadata/models/metadata.ts
server/src/tasks/tasks.service.ts

Metadata: Use 'class-validation' for better error handling and messages

---

front/src/api/api.ts
front/src/components/actions/update-illustration.tsx
front/src/components/contextual-menu/artist-contextual-menu.tsx
front/src/components/contextual-menu/release-contextual-menu.tsx
front/src/components/contextual-menu/release-track-contextual-menu.tsx
front/src/components/contextual-menu/track-contextual-menu.tsx
server/src/providers/musicbrainz/musicbrainz.provider.spec.ts

Front: Update Illustration Action

---

docs/src/setup/create-library.md
front/src/api/api.ts
front/src/components/actions/playlist.tsx
front/src/components/actions/update-illustration.tsx
front/src/components/appbar/global-library.ts
front/src/components/library-form.tsx
front/src/components/settings/libraries-settings.tsx
front/src/models/library.ts
front/src/pages/settings/[[...panel]].tsx
server/src/library/library.controller.spec.ts
server/src/library/library.controller.ts

Front: Library Creation and Update

---

front/src/api/api.ts
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/pages/releases/[slugOrId].tsx
server/src/artist/artist.controller.spec.ts
server/src/artist/artist.controller.ts
server/src/artist/artist.service.ts
server/src/artist/models/artist.query-parameters.ts

Front: Get Features Artists on Album Page

---

front/src/api/api.ts
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/pages/artists/[slugOrId]/index.tsx
server/src/album/album.controller.spec.ts
server/src/album/album.controller.ts
server/src/album/album.service.ts
server/src/album/models/album.query-parameters.ts

Get Albums where an artist appears

---

front/src/api/api.ts
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/pages/releases/[slugOrId].tsx
server/src/playlist/models/playlist.query-parameters.ts
server/src/playlist/playlist.controller.ts
server/src/playlist/playlist.service.spec.ts
server/src/playlist/playlist.service.ts

Get Playlists related to an album

---

server/src/song/song.service.ts

Song Versions: Selection is case-insensitive

---

front/src/components/player/player.tsx

Preventing multiple toast to appear when changing track before playback started

Front: Better Error Handling on playback fail

---

docs/src/setup/settings.md
server/src/metadata/metadata.service.ts
server/src/settings/models/settings.ts
server/src/settings/settings.service.ts
server/test/assets/settings-fake-regex.json
server/test/assets/settings-provider-disabled.json
server/test/assets/settings.json
server/test/assets/settings2.json

Closes #425
Also closes #429 on the fly

Configure 'Various Artists'

---

.github/workflows/unit-tests.yml
README.md
front/src/api/api.ts
front/src/components/illustration.tsx
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/pages/index.tsx
front/src/pages/releases/[slugOrId].tsx
server/src/album/album.controller.ts
server/src/album/album.service.ts
server/src/album/models/album.query-parameters.ts
server/src/genre/genre.controller.spec.ts
server/src/genre/genre.service.spec.ts
server/src/song/song.controller.ts
server/src/song/song.service.spec.ts
server/src/song/song.service.ts
server/src/video/video.service.spec.ts
server/yarn.lock

Get Related Albums & B-Sides

---

front/src/api/api.ts
front/src/components/actions/library-task.tsx
front/src/components/actions/refresh-metadata.tsx
front/src/components/contextual-menu/album-contextual-menu.tsx
front/src/components/contextual-menu/release-contextual-menu.tsx
front/src/components/contextual-menu/release-track-contextual-menu.tsx
front/src/components/contextual-menu/song-contextual-menu.tsx
front/src/components/contextual-menu/track-contextual-menu.tsx
front/src/components/settings/libraries-settings.tsx
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
server/src/library/library.service.ts
server/src/tasks/models/refresh-metadata.selector.ts
server/src/tasks/models/tasks.ts
server/src/tasks/tasks.controller.spec.ts
server/src/tasks/tasks.controller.ts
server/src/tasks/tasks.runner.ts
server/src/track/track.service.ts

Selective Metadata Refresh

---

front/src/components/release-tracklist.tsx
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/models/track.ts
server/prisma/migrations/20231207184811_bonus_track_field/migration.sql
server/prisma/schema.prisma
server/src/scanner/parser.service.spec.ts
server/src/scanner/parser.service.ts
server/src/scanner/scanner.service.ts
server/src/track/track.service.spec.ts

Add 'Bonus' Track metadata

---

front/src/components/highlight-card/album-highlight-card.tsx
front/src/components/infinite/infinite-resource-view/infinite-album-view.tsx
front/src/components/infinite/selectable-infinite-view.tsx
front/src/components/section-header.tsx
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/models/external-id.ts
front/src/pages/albums/index.tsx
front/src/pages/artists/[slugOrId]/albums.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/utils/album-type.ts

Front: Artist Page: Album sections

---

front/src/components/player/controls/slider.tsx
front/src/components/player/player.tsx
front/src/models/track.ts
front/src/pages/releases/[slugOrId].tsx
front/src/utils/formatDuration.ts
server/prisma/migrations/20231221132029_optional_bitrate_and_duration/migration.sql
server/prisma/schema.prisma
server/src/scanner/models/metadata.ts
server/src/scanner/scanner.service.spec.ts
server/src/scanner/scanner.service.ts
settings.json

Parse Embedded Metadata only if settings say so

---

front/src/components/controls/controls.tsx
front/src/components/icons.tsx
front/src/components/infinite/infinite-resource-view/infinite-song-view.tsx
front/src/components/infinite/selectable-infinite-view.tsx
front/src/components/player/controls.tsx
front/src/i18n/translations/en.ts
front/src/i18n/translations/fr.ts
front/src/pages/artists/[slugOrId]/songs.tsx
front/src/pages/genres/[slugOrId].tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/songs/[slugOrId]/[...tab].tsx
front/src/pages/songs/index.tsx
front/src/state/playerSlice.ts
server/src/repository/repository.service.ts
server/tsconfig.json

Kinda closes #293 
Definitely closes #572

Front: Play and Shuffle button for Song Lists

---

front/src/components/tile-row.tsx
front/src/components/tile/tile.tsx

Scale up the illustration on hover + handle Contextual Menus without JS

Front: tile animation and optimisation

---

server/src/providers/allmusic/allmusic.provider.ts
server/src/providers/discogs/discogs.provider.ts
server/src/providers/metacritic/metacritic.provider.ts
server/src/providers/wikipedia/wikipedia.provider.ts

Providers: Fix Some Broken Icon Links

---

front/src/components/highlight-card/highlight-card.tsx
front/src/components/illustration.tsx
front/src/components/relation-page-header/album-relation-page-header.tsx
front/src/components/relation-page-header/artist-relation-page-header.tsx
front/src/components/relation-page-header/song-relation-page-header.tsx
front/src/components/tile/album-tile.tsx
front/src/components/tile/artist-tile.tsx
front/src/components/tile/playlist-tile.tsx
front/src/components/tile/release-tile.tsx
front/src/components/tile/video-tile.tsx
server/package.json
server/src/illustration/illustration.service.ts
server/src/illustration/models/illustration-quality.ts
server/yarn.lock

Illustration: Add Quality Presets + Cache resized images

---

server/src/illustration/illustration.repository.ts
server/src/illustration/illustration.service.ts

Server: Rename resized images + delete them if parent file is deleted

---

front/src/api/api.ts
front/src/api/use-query.ts
front/src/components/authentication/authentication-wall.tsx
front/src/ssr.ts
server/src/authentication/authentication.exception.ts
server/src/authentication/jwt/jwt.strategy.ts
server/src/user/models/user.query-params.ts
server/src/user/user.exceptions.ts
server/src/user/user.service.ts

Authentication: Fix HTTP Response when Bad Token + Disable SSR Prefetch if Auth failed

---

server/src/repository/repository.service.ts
server/src/song/song.controller.ts

Server: Fix WhereInput when using random

---

front/src/components/infinite/infinite-resource-view/infinite-song-view.tsx
front/src/components/track-file-info.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/models/song.ts
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/index.tsx
server/prisma/migrations/20240131095559_play_history/migration.sql
server/prisma/schema.prisma
server/src/song/models/song.query-params.ts
server/src/song/song.controller.spec.ts
server/src/song/song.controller.ts
server/src/song/song.service.spec.ts
server/src/song/song.service.ts

Play History + Sort By Play Count

---

front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/models/song.ts
server/package.json
server/prisma/migrations/20240609094144_medley_song_type/migration.sql
server/prisma/schema.prisma
server/src/scanner/parser.service.spec.ts
server/src/scanner/parser.service.ts
server/yarn.lock

Add Medley Song Type

---

server/src/illustration/illustration.service.ts
server/src/scanner/parser.service.spec.ts
server/src/scanner/parser.service.ts

Nested dashed group

---

front/src/components/infinite/infinite-resource-view/infinite-song-view.tsx
front/src/components/player/controls.tsx
front/src/pages/releases/[slugOrId].tsx

Front: fix video playback with player's tabs

---

.env.example
docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml
settings.json

Documentation fixes

---

front/src/models/song.ts
front/src/pages/artists/[slugOrId]/index.tsx
server/src/providers/wikipedia/wikipedia.provider.spec.ts
server/src/song/models/song.query-params.ts
server/src/song/song.service.ts

Sort songs by release date

---

front/src/components/tile/release-tile.tsx

Front: Fix skeleton on release tile when release date is null

---

front/src/components/error-page.tsx
front/src/components/head.tsx
front/src/components/player/player.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/pages/albums/index.tsx
front/src/pages/artists/[slugOrId]/albums.tsx
front/src/pages/artists/[slugOrId]/index.tsx
front/src/pages/artists/[slugOrId]/songs.tsx
front/src/pages/artists/[slugOrId]/videos.tsx
front/src/pages/artists/index.tsx
front/src/pages/genres/[slugOrId].tsx
front/src/pages/playlists/[slugOrId]/index.tsx
front/src/pages/playlists/index.tsx
front/src/pages/releases/[slugOrId].tsx
front/src/pages/search/[[...query]].tsx
front/src/pages/settings/[[...panel]].tsx
front/src/pages/songs/[slugOrId]/[...tab].tsx
front/src/pages/songs/index.tsx
front/src/pages/videos/index.tsx

Front: Set Title in HTML Head for each page

---

front/src/components/infinite/infinite-grid.tsx
front/src/components/tile-row.tsx
front/src/pages/index.tsx

Front: Set better grid cols count on xl viewports

---

front/src/components/player/player.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json

Front: alert before leaving when playing

---

docker-compose.dev.yml
docker-compose.prod.yml
docker-compose.yml

Update Docker compose following a breaking change with the transcoder

Transcoder: Update Docker-compose with new env var

---

front/package.json
front/src/components/keyboard-bindings-modal.tsx
front/src/components/player/player.tsx
front/src/components/settings/user-settings.tsx
front/src/contexts/keybindings.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/pages/_app.tsx
front/src/pages/index.tsx
front/src/pages/search/[[...query]].tsx
front/yarn.lock

Front: Basic keyboard bindings

---

README.md
front/src/api/api.ts
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/pages/releases/[slugOrId].tsx
server/src/release/release.controller.ts
server/src/track/models/track.query-parameters.ts
server/src/track/track.service.ts

Exclusive songs

---

server/src/album/album.service.ts
server/src/repository/repository.utils.ts
server/src/song/song.service.ts
server/src/utils/shuffle.ts

Server: Rework getting random songs/albums by shuffling outside database

---

.github/workflows/matcher.yml
matcher/matcher/__main__.py
matcher/matcher/api.py
matcher/matcher/settings.py
matcher/requirements.txt
matcher/tests/__main__.py
matcher/tests/api.py
matcher/tests/assets/bad_type.json
matcher/tests/assets/missing_field.json
matcher/tests/assets/settings.json
matcher/tests/settings.py

Matcher: Read settings

---

front/src/api/api.ts
front/src/components/infinite/infinite-resource-view/infinite-video-view.tsx
front/src/models/song.ts
front/src/pages/artists/[slugOrId]/videos.tsx
front/src/pages/videos/index.tsx
server/src/video/video.service.ts

Filter Videos by type

---

front/src/components/infinite/infinite-resource-view/infinite-video-view.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/models/song.ts
server/prisma/migrations/20241212090123_fix_acappella_spelling/migration.sql
server/prisma/schema.prisma
server/src/parser/parser.service.spec.ts
server/src/parser/parser.service.ts

Server: Fix Spelling of 'Acappella'

---

matcher/matcher/matcher/album.py
matcher/matcher/models/api/domain.py
matcher/matcher/providers/discogs.py
matcher/matcher/providers/genius.py
matcher/matcher/providers/musicbrainz.py
matcher/matcher/utils.py
matcher/tests/providers/discogs.py
matcher/tests/providers/genius.py
matcher/tests/providers/musicbrainz.py
matcher/tests/providers/wikipedia.py
server/src/album/album.service.ts

Biggest fix is preventing album date to be overwritten by new release's if it's been found by the matcher

Matcher: Various Fixes

---

matcher/matcher/api.py
matcher/matcher/matcher/album.py
matcher/matcher/models/api/domain.py
matcher/matcher/models/api/dto.py
matcher/matcher/providers/boilerplate.py
matcher/matcher/providers/domain.py
matcher/matcher/providers/features.py
matcher/matcher/providers/musicbrainz.py
matcher/tests/matcher/album.py
matcher/tests/providers/musicbrainz.py

Matcher: Get Album type

---

server/src/release/release.service.ts
server/src/song/song.service.ts

Server: BSides across albums

---

front/src/components/actions/link.tsx
front/src/components/contextual-menu/song-contextual-menu.tsx
front/src/components/contextual-menu/track-contextual-menu.tsx
front/src/components/list-item/song-item.tsx
front/src/components/list-item/track-item.tsx
front/src/components/player/controls.tsx
front/src/models/track.ts
front/src/pages/artists/[slugOrId]/songs.tsx
front/src/pages/playlists/[slugOrId]/index.tsx
scanner/internal/api/api.go
scanner/internal/metadata.go
scanner/internal/parser/parser_test.go
server/prisma/migrations/20241221080934_track_thumbnail/migration.sql
server/prisma/migrations/20241221104003_standalone_track_illustration/migration.sql
server/prisma/migrations/20241221112653_standalone_track/migration.sql
server/prisma/schema.prisma
server/src/illustration/illustration.controller.spec.ts
server/src/illustration/illustration.repository.ts
server/src/registration/metadata.service.ts
server/src/registration/models/metadata-saved.dto.ts
server/src/registration/models/metadata.ts
server/src/registration/registration.controller.spec.ts
server/src/registration/registration.service.ts
server/src/release/release.service.ts
server/src/song/song.service.ts
server/src/track/models/track.query-parameters.ts
server/src/track/models/track.response.ts
server/src/track/track.service.ts
server/src/video/video.controller.spec.ts
server/test/expected-responses.ts

Add support for tracks that do not belong to a release (Closes #689)

Standalone Tracks

---

.github/workflows/server.yml
server/Dockerfile
server/Dockerfile.dev
server/package.json
server/yarn.lock

Server: Bump node version

---

.github/workflows/scanner.yml
scanner/internal/parser/embedded.go

Allow for more flexibility in getting values from ffprobe's output

Scanner: Fix to support uppercase keys in ffprobe output

---

front/package.json
front/src/api/api.ts
front/src/components/actions/refresh-metadata.tsx
front/src/components/tile/tile.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/yarn.lock
scanner/app/routes.go
scanner/internal/tasks/refresh.go

Scanner: Allow forcing metadata refresh

---

scanner/app/routes.go
scanner/internal/tasks/clean.go
scanner/internal/tasks/common.go
scanner/internal/tasks/refresh.go
scanner/internal/tasks/scan.go
scanner/internal/tasks/worker.go

The `/tasks` endpoint give the progress of the current task

Scanner: Task Progress

---

matcher/matcher/providers/genius.py
matcher/matcher/providers/wikidata.py

The skeleton of the lyrics page changed on Genius. This PR fixes the selection of the lyrics

Matcher: Genius: Fix selector on Lyrics

---

front/src/components/controls/controls.tsx
front/src/components/icons.tsx
front/src/components/infinite/infinite-grid.tsx
front/src/components/infinite/infinite-resource-view/infinite-album-view.tsx
front/src/components/infinite/infinite-resource-view/infinite-artist-view.tsx
front/src/components/infinite/infinite-resource-view/infinite-playlist-view.tsx
front/src/components/infinite/infinite-resource-view/infinite-resource-view-props.ts
front/src/components/infinite/infinite-resource-view/infinite-song-view.tsx
front/src/components/infinite/infinite-resource-view/infinite-track-view.tsx
front/src/components/infinite/infinite-resource-view/infinite-video-view.tsx
front/src/components/infinite/infinite-view.tsx
front/src/pages/search/[[...query]].tsx
front/src/utils/layout.ts

Change Grid's Items size

---

.github/workflows/front.yml
.github/workflows/matcher.yml
.github/workflows/scanner.yml
.github/workflows/server.yml

Revert "CI: Docker: Build Docker Images for ARM"

---

server/package.json
server/yarn.lock

Fixes https://github.com/Arthi-chaud/Meelo/security/dependabot/124

Server: Bump Nestjs CLI

---

front/src/utils/gradient-background.tsx

Use atoms to manage state + SSR
Fixes #929

Front: Fix Gradient Background Flash

---

front/src/api/api.ts
front/src/components/library-form.tsx
server/src/library/library.controller.spec.ts
server/src/library/library.exceptions.ts
server/src/library/models/create-library.dto.ts
server/src/registration/registration.controller.spec.ts
server/src/registration/registration.service.ts
server/test/test-prisma.service.ts

Allow library path to be ‘./‘

---

front/src/api/use-query.ts
front/src/components/infinite/controls/controls.tsx
front/src/components/infinite/resource/song.tsx
front/src/components/infinite/resource/video.tsx
front/src/components/player/controls/expanded.tsx
front/src/components/player/index.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/state/player.ts

Allow Player's Queue to be 'infinite' (i.e. rely on paginated Queries)
Closes #939

Front: Lazyload  Queue

---

front/src/api/index.ts
front/src/components/actions/merge.tsx
front/src/components/actions/playlist.tsx
front/src/components/actions/refresh-metadata.tsx
front/src/components/contextual-menu/resource/song.tsx
front/src/components/contextual-menu/resource/track.tsx
front/src/components/icons.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
server/src/song/models/merge-song.dto.ts
server/src/song/song.controller.spec.ts
server/src/song/song.controller.ts
server/src/song/song.service.ts
server/src/track/models/update-track.dto.ts
server/src/track/track.controller.spec.ts
server/src/track/track.controller.ts
server/src/track/track.service.spec.ts
server/src/track/track.service.ts

Merge Songs and reassign tracks

---

.env.example
README.md
front/src/api/index.ts
front/src/api/queries.ts
front/src/components/icons.tsx
front/src/components/player/index.tsx
front/src/components/settings/ui.tsx
front/src/i18n/translations/en.json
front/src/i18n/translations/fr.json
front/src/middleware.ts
front/src/models/scrobblers.ts
server/README.md
server/package.json
server/prisma/migrations/20250518085251_scrobblers/migration.sql
server/prisma/schema.prisma
server/prisma/types.d.ts
server/src/app.module.ts
server/src/scrobbler/models/lastfm.dto.ts
server/src/scrobbler/models/listenbrainz.dto.ts
server/src/scrobbler/models/scrobblers.response.ts
server/src/scrobbler/scrobbler.controller.spec.ts
server/src/scrobbler/scrobbler.controller.ts
server/src/scrobbler/scrobbler.exceptions.ts
server/src/scrobbler/scrobbler.module.ts
server/src/scrobbler/scrobbler.service.ts
server/src/scrobbler/scrobblers/lastfm.scrobbler.ts
server/src/scrobbler/scrobblers/listenbrainz.scrobbler.ts
server/src/scrobbler/scrobblers/scrobbler.ts
server/yarn.lock

Add support for scrobbling with ListenBrainz and LastFM
Closes #703 
TODO:

Scrobbler Support

---

front/apps/web/src/components/authentication/form.tsx
front/packages/api/src/queries.ts
front/packages/models/src/settings.ts
server/src/authentication/authentication.controller.spec.ts
server/src/settings/models/settings.ts
server/src/settings/settings.controller.spec.ts
server/src/settings/settings.controller.ts
server/src/settings/settings.service.spec.ts
server/src/settings/settings.service.ts
server/src/user/user.controller.ts
server/src/user/user.module.ts

Disable user registration

---

front/apps/web/src/pages/artists/[slugOrId]/index.tsx
front/apps/web/src/pages/songs/[slugOrId]/[...tab].tsx
front/packages/components/src/actions/resource-type.tsx
front/packages/components/src/infinite/resource/album.tsx
front/packages/components/src/infinite/resource/song.tsx
front/packages/components/src/infinite/resource/video.tsx
front/packages/components/src/track-file-info.tsx
front/packages/models/src/album.ts
front/packages/models/src/utils.ts
front/packages/models/tsconfig.json
front/translations/en.json
front/translations/fr.json
matcher/matcher/providers/domain.py
matcher/matcher/providers/musicbrainz.py
matcher/tests/providers/musicbrainz.py
server/prisma/migrations/20250620140618_ep_album_type/migration.sql
server/prisma/schema.prisma
server/src/parser/parser.service.spec.ts
server/src/parser/parser.service.ts

EP album type

---

front/packages/api/src/queries.ts
server/src/artist/artist.controller.spec.ts
server/src/artist/artist.controller.ts
server/src/artist/artist.service.spec.ts
server/src/artist/artist.service.ts
server/src/artist/models/artist.query-parameters.ts

Filter for 'primary' artists

---

server/src/stream/stream.service.ts

Blocked by https://github.com/zoriya/Kyoo/pull/1025

Server: Use prefix for transcoder

---

.github/actions/dockerize/action.yml
docker-compose.yml
scanner/Dockerfile
scanner/Dockerfile.dev
scanner/app/main.go
scanner/app/routes.go

A first step/attempt for #1027

Scanner: Embed App Version

---

front/apps/mobile/src/app/(protected)/(home,browse,search)/_layout.tsx
front/apps/mobile/src/components/background-gradient.tsx

Seems to make navigation slightly more tolerable

Mobile: DRY Stacks with shared routes

---

README.md

README: New screenshots + minor refacto

---

front/apps/mobile/src/actions/add-to-playlist.tsx
front/apps/mobile/src/app/(protected)/(home)/index.tsx
front/apps/mobile/src/components/context-menu/resource/album.ts
front/apps/mobile/src/components/context-menu/resource/artist.ts
front/apps/mobile/src/components/context-menu/resource/playlist.ts
front/apps/mobile/src/components/context-menu/resource/release.ts
front/apps/mobile/src/components/context-menu/resource/song.ts
front/apps/mobile/src/components/context-menu/resource/track.ts
front/apps/mobile/src/components/context-menu/resource/video.ts
front/apps/web/src/components/actions/playlist.tsx
front/apps/web/src/components/contextual-menu/resource/album.tsx
front/apps/web/src/components/contextual-menu/resource/artist.tsx
front/apps/web/src/components/contextual-menu/resource/playlist.tsx
front/apps/web/src/components/contextual-menu/resource/release-track.tsx
front/apps/web/src/components/contextual-menu/resource/release.tsx
front/apps/web/src/components/contextual-menu/resource/song.tsx
front/apps/web/src/components/contextual-menu/resource/track.tsx
front/apps/web/src/components/contextual-menu/resource/video.tsx
front/apps/web/src/components/player/controls/expanded.tsx
front/packages/api/src/index.ts
front/translations/en.json
front/translations/fr.json
server/src/playlist/models/playlist.dto.ts
server/src/playlist/playlist.controller.ts
server/src/playlist/playlist.exceptions.ts
server/src/playlist/playlist.service.ts

Server: add album, artist and playlist to playlist

---

front/apps/mobile/src/app/(protected)/(home,browse,search)/artists/[id].tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/songs/index.tsx
front/apps/mobile/src/components/item/resource/song.tsx
front/apps/mobile/src/components/song-grid.tsx
front/apps/mobile/src/pages/release/index.tsx
front/apps/mobile/src/pages/release/tracklist.tsx
front/apps/web/src/components/list-item/resource/song.tsx
front/apps/web/src/components/page-section.tsx
front/apps/web/src/components/release-tracklist.tsx
front/apps/web/src/components/song-grid.tsx
front/apps/web/src/pages/artists/[slugOrId]/songs.tsx
front/apps/web/src/pages/releases/[slugOrId].tsx
front/packages/utils/src/format-artists.ts

When a song / track list is related to a given artist, we avoid repeating that main artist's name and add a `Feat.` prefix
TODO

Front: 'Feat.' Prefix when formatting artists

---

front/apps/mobile/src/app/(protected)/(home,browse,search)/_layout.tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/artists/[id].tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/playlists/[id].tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/songs/[id].tsx
front/apps/mobile/src/app/(protected)/_layout.tsx
front/apps/mobile/src/components/chip.tsx
front/apps/mobile/src/components/illustration.tsx
front/apps/mobile/src/pages/release/index.tsx
front/apps/mobile/src/pages/release/tracklist.tsx
front/apps/mobile/src/primitives/pressable.tsx
front/apps/web/src/components/contextual-menu/resource/video.tsx
front/apps/web/src/pages/releases/[slugOrId].tsx
front/packages/ui/src/pages/release.tsx

Use 'useState' instead of 'useMemo' to make first render easier and only render footer when the page's main resource is loaded

Mobile: Make navigation faster

---

front/apps/mobile/src/app/(protected)/(browse)/index.tsx
front/apps/mobile/src/app/(protected)/(home)/index.tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/_layout.tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/albums/index.tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/genres.tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/songs/[id].tsx
front/apps/mobile/src/app/(protected)/(home,browse,search)/songs/index.tsx
front/apps/mobile/src/components/context-menu/resource/genre.ts
front/apps/mobile/src/components/item/list-item.tsx
front/apps/mobile/src/components/item/resource/genre.tsx
front/apps/mobile/src/pages/release/index.tsx
front/translations/en.json
front/translations/fr.json

Mobile: Genre Chip, List Item and Pages

---

server/src/search/search.service.ts

Reverts Arthi-chaud/Meelo#1175

Revert "Make search ordering fairer in regard of artists"
